server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: firm

  jpa:
    show-sql: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:firm}?currentSchema=${DB_SCHEMA:firm}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Firm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
jwt:
  auth:
    converter:
      resource-id: firm-rest-api
      principle-attribute: preferred_username
api:
  auth:
    url: http://localhost:8080

auth:
  client-id: firm-rest-api
  grant-type: password

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: firm
    description: This is firm application

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    groups-order: DESC
    path: /swagger-ui.html
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'

logging:
  pattern:
    console: "%clr(%d{dd:yy:MM:HH:mm}){faint}%clr(${LOG_LEVEL_PATTERN:-%-5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    com.andersen.weather.service: debug
